### ISSUE TITLE
issue with parser

### ISSUE THREAD

**Issue by Bishamon1987** [barthoekstra/knmy#1]
When I try using this example code I get the following error.
Am I doing something wrong or is this script out of date?

```
Traceback (most recent call last):
  File "W:\Some_map\knmi.py", line 3, in <module>
    disclaimer, stations, variables, data = knmy.get_hourly_data(stations=[209, 235], start=2022061715, end=2022061716, inseason=True, variables=['WIND', 'TEMP'], parse=True)
  File "C:\Users\some_name\AppData\Local\Programs\Python\Python39\lib\site-packages\knmy\knmy.py", line 214, in get_hourly_data
    return get_knmi_data('hourly', stations=stations, start=start, end=end, variables=variables, inseason=inseason,
  File "C:\Users\some_name\AppData\Local\Programs\Python\Python39\lib\site-packages\knmy\knmy.py", line 136, in get_knmi_data
    return parse_raw_weather_data(r.text)
  File "C:\Users\some_name\AppData\Local\Programs\Python\Python39\lib\site-packages\knmy\parser.py", line 31, in parse_raw_weather_data
    stations_raw = next(chunk)
StopIteration
```

**Comment by barthoekstra** [comment]
I haven't updated the package in a while and don't use it regularly, so it could be that it has gotten out of sync with the KNMI API. I'll have a look into it 2 weeks from now.

**Comment by JopWerff** [comment]
Beste Bart,

Wij hebben al eens eerder contact met elkaar gehad inzake jouw package KNMI.

Ik reageer hier even om ook aan te geven dat ook ik zeker geïnteresseerd
ben in een update van je tools om KNMI-data makkelijk binnen te halen.
Dus heel graag.

Ik heb wel de indruk dat het KNMI de API nogal sterk gewijzigd heeft.

Krijgen wij automatisch een seintje, zodra je je voorgenomen update
gerealiseerd hebt?

Alvast bedankt,

   Jop van der Werff


tel.: +31 318 693199
gsm: +31 6 55 720 770


Op za 18 jun. 2022 om 09:37 schreef Bart Hoekstra ***@***.***

**Comment by barthoekstra** [comment]
It turned out there are, indeed, quite a few changes that KNMI has made to this particular API recently. Took a bit more time to rework my code than expected, but it should work again now. Thanks for your patience.

Beware, some things have unfortunately changed considerably, more details [in the release](https://github.com/barthoekstra/knmy/releases/tag/1.5.1). Nevertheless, it shouldn't be a problem to get things up and running again.

You can install/reinstall using:

```
pip install knmy --upgrade
```

Please let me know if you encounter issues.

**Comment by JopWerff** [comment]
Hoi Bart,

Graag wil ik weer eens jouw KNMY gebruiken. We hebben al vaker contact
gehad.
Ik ben - wegens lange tijd niet gebruiken - er wel weer een beetje uit.
Bij het KNMI is er geloof ik enorm veel veranderd in het systeem om data
binnen te halen.

Is de documentatie die ik hier vind up to date?
https://knmy.readthedocs.io/en/latest/

Ik werk op een iMac. Waar het nog niet op geïnstalleerd staat.
Dat lijkt met kunst en vliegwerk gelukt... ik moest met brew installeren en
nog wat trucs daarbij.

Wil het nu testen maar dat lukt me nog niet goed. Ik kan ook geen
voorbeelden vinden.

Zou jij me aan een voorbeeld py-script kunnen helpen om de 10-minuten data
van T en van T10 te downloaden voor de weerstations Eelde en Hupsel. En dan
vanaf de datum zo 7 januari t/m wo 10 januari 2024, dus jongstleden januari?

Ik ga ervan uit dat zo'n script voor jou vrij snel te schrijven is. Of dat
je al iets hebt liggen dat ik als voorbeeld kan gebruiken.

Als ik zoiets werkend heb en een duidelijk voorbeeld, dan kom ik zelf wel
verder.

Je hebt denk ik wel meegekregen dat Winterswijk op 9 januari jl. op een
indrukwekkende manier de EMON (Eerste Marathon op Natuurijs) heeft
binnengehaald.
En dat wil ik nu even evalueren aan de hand van de temperatuurdata rond die
dagen en vooral de hele aanloop naar de 9e en de 10e januari toe.

Ik hoop dat ik niet te veel vraag.

Met vriendelijke groet,

    Jop




tel.: +31 318 693199
gsm: +31 6 55 720 770


Op zo 14 aug 2022 om 00:11 schreef Bart Hoekstra ***@***.***>:
